[server]
hostname = "vpn.example.com"
port = 443
hub = "DEFAULT"
use_ssl = true
verify_certificate = true
timeout = 30
keepalive_interval = 30

[auth]
username = "testuser"
password = "testpassword"
# Optional certificate-based authentication
# client_cert = "path/to/client.crt"
# client_key = "path/to/client.key"

[network]
enable_ipv6 = false
enable_http2 = true
tcp_keepalive = true
tcp_nodelay = true

[logging]
level = "info"
# Optional file logging
# file = "rvpnse.log"
