# VPN Gate test configuration
# Server: public-vpn-247.opengw.net (219.100.37.188)
# Credentials: vpn/vpn

[server]
hostname = "public-vpn-247.opengw.net"
port = 443
hub = "VPNGATE"
use_ssl = true
verify_certificate = false
timeout = 30
keepalive_interval = 50

[auth]
method = "password"
username = "vpn"
password = "vpn"

[network]
auto_route = false
dns_override = false
dns_servers = []
mtu = 1500
custom_routes = []
exclude_routes = []

[logging]
level = "info"
file_logging = false
