# rVPNSE Production Configuration Example
# This configuration demonstrates connection limits and production settings

[server]
hostname = "vpn.example.com"
port = 443
hub = "VPN"
use_ssl = true
verify_certificate = true
timeout = 30
keepalive_interval = 60

[connection_limits]
# Production connection limits
max_concurrent_connections = 100
max_connections_per_minute = 60
max_retry_attempts = 5
retry_delay = 10
connection_queue_size = 20

# Future pooling configuration
enable_connection_pooling = false
pool_idle_timeout = 300
pool_max_lifetime = 3600

[auth]
method = "password"
username = "vpnuser"
password = "secure_password_here"
save_username = true

[vpn]
adapter_name = "rVPNSE"
mtu = 1500
use_compression = true
auto_reconnect = true
max_reconnect_attempts = 10
reconnect_delay = 5

[advanced]
# Advanced protocol settings
protocol_version = "4.0"
cipher_suite = "AES256-GCM"
enable_nat_traversal = true
udp_acceleration = true
