# RVPNSE Mobile Configuration Example
# Optimized for mobile devices with battery and data usage considerations

[server]
hostname = "mobile-vpn.example.com"
port = 443
hub = "Mobile"
use_ssl = true
verify_certificate = true
timeout = 45
keepalive_interval = 120

[connection_limits]
# Mobile-optimized limits
max_concurrent_connections = 2
max_connections_per_minute = 6
max_retry_attempts = 3
retry_delay = 15
connection_queue_size = 5

# Disable pooling for mobile
enable_connection_pooling = false

[auth]
method = "password"
username = "mobile_user"
password = "mobile_password"
save_username = true

[vpn]
adapter_name = "RVPNSEMobile"
mtu = 1280  # Smaller MTU for mobile networks
use_compression = true
auto_reconnect = true
max_reconnect_attempts = 5
reconnect_delay = 10

[advanced]
# Mobile-optimized settings
protocol_version = "4.0"
cipher_suite = "AES128-GCM"  # Lighter encryption for mobile
enable_nat_traversal = true
udp_acceleration = false     # May not work reliably on mobile networks
