# SoftEther SSL-VPN Configuration Example
# This file demonstrates the configuration format for Rust VPNSE static library

[server]
# Server hostname or IP address
hostname = "vpn.example.com"

# Server port (default: 443 for HTTPS)
port = 443

# Hub name to connect to (required)
hub = "VPN"

# Use SSL/TLS connection (default: true)
use_ssl = true

# Verify server certificate (default: true)
verify_certificate = true

# Connection timeout in seconds (default: 30)
timeout = 30

# Keep-alive interval in seconds (default: 60)
keepalive_interval = 60

[auth]
# Authentication method: "password", "certificate", or "anonymous"
method = "password"

# Username for password authentication
username = "your_username"

# Password for password authentication  
password = "your_password"

# For certificate authentication (uncomment and set paths):
# certificate_path = "/path/to/client.crt"
# private_key_path = "/path/to/client.key"
# certificate_password = "cert_password_if_needed"

[network]
# Virtual network interface name (will be created by your app)
interface_name = "vpnse0"

# Network address for the VPN interface (your app sets this)
address = "10.0.0.2"

# Network mask (your app sets this)
netmask = "255.255.255.0"

# Gateway address (your app sets this)
gateway = "10.0.0.1"

# DNS servers (your app configures these)
dns_servers = ["8.8.8.8", "8.8.4.4"]

# Enable automatic routing (your app implements this)
auto_route = true

# Enable IPv6 support (your app implements this)
ipv6 = false

[logging]
# Log level: "error", "warn", "info", "debug", "trace"
level = "info"

# Log to file (optional)
# file_path = "/var/log/vpnse.log"

# Enable console logging
console = true
