[server]
host = "public-vpn-247.opengw.net"
port = 443
use_ssl = true

[authentication]
username = "vpn"
password = "vpn"
hub_name = "VPNGATE"

[connection]
timeout_seconds = 30
keep_alive_interval = 60
retry_attempts = 3

[logging]
level = "info"
