name: Benchmarks

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'benches/**'
      - 'Cargo.toml'
  schedule:
    # Run weekly on Sundays at midnight UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Run benchmarks
      run: |
        # Create output directory
        mkdir -p benchmark-results
        
        # Run benchmarks and capture output
        echo "# Benchmark Results" > benchmark-results/report.md
        echo "Generated on: $(date)" >> benchmark-results/report.md
        echo "" >> benchmark-results/report.md
        
        # Run each benchmark individually for better control
        echo "## Client Benchmarks" >> benchmark-results/report.md
        cargo bench --bench client_benchmarks 2>&1 | tee -a benchmark-results/report.md
        
        echo -e "\n## Configuration Benchmarks" >> benchmark-results/report.md
        cargo bench --bench config_benchmarks 2>&1 | tee -a benchmark-results/report.md
        
        echo -e "\n## FFI Benchmarks" >> benchmark-results/report.md
        cargo bench --bench ffi_benchmarks 2>&1 | tee -a benchmark-results/report.md
        
        # Copy criterion results if they exist
        if [ -d "target/criterion" ]; then
          cp -r target/criterion benchmark-results/
        fi

    - name: Store benchmark results
      run: |
        # Check if benchmark results were generated
        if [ -f "benchmark-results/report.md" ]; then
          echo "Benchmark results generated successfully"
          echo "Results summary:"
          tail -n 20 benchmark-results/report.md
        else
          echo "Warning: No benchmark results found"
        fi

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark-results/
